### ISSUE TITLE
Event to update items

### ISSUE THREAD

**Issue by kirantpatil** [g1velo/SNAVXbee2#9]
Hi @g1velo,

Why there is no usage of Events to update items ?

Thanks.

**Comment by kirantpatil** [comment]
Below is code from [openhab-1 addon](https://github.com/openhab/openhab1-addons/blob/master/bundles/binding/org.openhab.binding.diyonxbee/src/main/java/org/openhab/binding/diyonxbee/internal/DiyOnXBeeBinding.java).

```
private void tryUpdate(final String key, final String value, final String remoteAddress) {
		logger.debug("trying to set {} of {} to {}", key, remoteAddress, value);
		boolean updated = false;
		for (final DiyOnXBeeBindingProvider provider : providers) {

			for (final String itemName : provider.getItemNames()) {
				final String id = provider.getId(itemName);
				final String remote = provider.getRemote(itemName);

				if (key.equals(id) && remote.equals(remoteAddress)) {
					final List<Class<? extends State>> availableTypes = provider.getAvailableItemTypes(itemName);
					final State state = parseState(value, availableTypes, provider, itemName);
					if (state != null) {
						updated = true;
						eventPublisher.postUpdate(itemName, state);
					}
				}
			}
}
```

**Comment by g1velo** [comment]
Hi, 
 I took as an example the YahooWeather binding where : 
updateState(channelUID, getTemperature());

Is used. I have seen no mention of eventPublisher in OH2 binding, but I am not expert enough to tell if we should use it. 

In my case the updateState call works fine an items are updated. 
You can try to run : 
smarthome:status ItemName 

TO check is it is updated.

**Comment by kirantpatil** [comment]
Yes, events are getting generated. Somehow I overlooked it. Thanks.
